### PR TITLE
Adaptations for joomla_4.0

### PR DESCRIPTION
**Pull request by JLTRY**
use ArrayHelper for joomla_4.0
use document.getElementById instead of document.id

### CODE REVIEW

**Comment by exstreme** [comment]
I think it's a bad idea to combine different versions and make crutches, I think it's much more productive to make a separate version for Joomla 4

**Comment by JLTRY** [comment]
I already wrote changes for Joomla_4.0 that you accepted See #35

**Comment by exstreme** [comment]
I will rollback this changes and try adapt https://github.com/exstreme/Jcomments-4 to Joomla 4

**Comment by exstreme** [comment]
Thank you, implemented

**Pull request closed without merging**
